import React from 'react'
import NamesContainer from '../SongsContainer/index.jsx'
import styles from './style.module.css'

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSearch } from '@fortawesome/free-solid-svg-icons'

class Songs extends React.Component{
state={
    names:[
        '1. Ako te pitaju (Grašo)',
        '2. Dani i godine (Nina)',
        '3. Samo s tobom sam upoznao ljubav (Oliver &amp; Skugor)',
        '4. Dodiri od stakla (N. Badric)',
        '5. Kad zena zavoli (T. Cetinski)',
        '6. Malo je dana (Halid)',
        '7. Stranac u noci (Masimo &amp; Nina)',
        '8. Ne ide vino bez harmonike',
        '9. Marija (Vigor)',
        '10. Zivot je raj (Vigor)',
        '11. Sta mi ljube oćeš kazat (Amulic)',
        '12. Vidi se iz aviona (Domenica)',
        '13. Ljubavna limunada (Domenica)',
        '14. Zadnja zelja',
        '15. Kad pijem vino (Mjesni odbor)',
        '16. Živim za to (Jacques Houdek)',
        '17. Kad nekoga voliš (Jacques Houdek)',
        '18. Udajem se (J. Rozga)',
        '19. Moderna žena (J. Rozga)',
        '20. Pismo glava (J. Rozga)',
        '21. Volim barabu (Danijela)',
        '22. Ti si mi u mislima (D. Dvornik)',
        '23. Ella e (D. Dvornik)',
        '24. 92 godine (P.Grašo)',
        '25. Ledena (Tose)',
        '26 Dio tebe (Nola)',
        '27. Tvoja prva djevojka (Severina)',
        '28. Unomomento (Severina)',
        '29. Italijana (Severina)',
        '30. Rujno vino (Pejakovic)',
        '31. Hajde nocas mi dodji - D. Merlin',
        '32. Gdje sam bio (Bebek)',
        '33.Ja po kafanama (Bebek)',
        '34. Djevojka sa cardas nogama (D. Balasevic)',
        '35. Svileni (Magazin)',
        '36. List duhana (Hari &amp; Doris)',
        '37. Lindo (Gracija)',
        '38. Ne pijem, ne pusim (J. Rozga)',
        '39. Ti zivis u oblacima mala (Z. Colic)',
        '40. Pusti pusti modu (Colic)',
        '41. Gutljaj vina (Magazin)',
        '42. Ako poludim (Magazin)',
        '43. Rano ranije (Magazin)',
        '44. Opijum (Magazin)',
        '45. Ja sam za ples (Tajci)',
        '46. 17 mi je godina (Tajci)',
        '47. Hajde da ludujemo (Tajci)',
        '48. Dobitna kombinacija (J. Rozga)',
        '49. Moj mali je opasan (Tajci)',
        '50. Drska zeno plava (Z. Joksimovic)',
        '51. Levisice (Danijel)',
        '52. Zbogom pameti (Zak)',
        '53. Dobro mi došla ljubavi (Gulijano)',
        '54. Srna i vuk (Guliano)',
        '55.Oko moje sanjivo (Magazin)',
        '56. Ljube se dobri losi (Magazin)',
        '57. Kokolo moj (Magazin)',
        '58. Dobra stara vremena mix (Razni izvodači)',
        '59. Dodirni mi koljena (Severina)',
        '60. Ena (Haustor)',
        '61. Srce za vodiča (Grašo)',
        '62. Ne mogu te prestat ljubit (Bralic)',
        '63. Zalutali pogled (Bralic)',
        '64. Kadi su ta vrata (Gustafi)',
        '65. Ja nisan stija mala (Gustafi)',
        '66. Zorica (Mejasi)',
        '67. Mata (Skoro)',
        '68. Juliska (Skoro)',
        '69. Karanfili (Nives Celzijus)',
        '70. Brkica (Gustafi)',
        '71. Lutka (S.A.R.S.)',
        '72. Sinoc sam pola kafane popio (Bebek)',
        '73. Tijana (Bebek)',
        '74. Stari lav (Ž. Samarđić)',
        '75. Morski vuk (Oliver &amp; Tony)',
        '76. Tražena si roba (Vuco)',
        '77. Tarapana (Severina)',
        '78. Brad Pitt (Severina)',
        '79. Italiana (Severina)',
        '80. Okus mentola (J. Rozga)',
        '81. Obožavam (J. Rozga)',
        '82. Tsunami (J. Rozga)',
        '83. Vozacka (L. Bacic)',
        '84. Viski (L. Bacic)',
        '85. Uzorita (Grdovic &amp; Bralic)',
        '86. Ne diraj moju ljubav (Klapa Sufit)',
        '87. Nakon svih ovih godina (P. Valjak)',
        '88. Tvoja mala (I. Kovač)',
        '89. No, no, no (Magazin)',
        '90. Kad zamirisu jorgovani (D. Merlin)',
        '91. Da je srece bilo (Bebek)',
        '92. Moje zlato (Grašo)',
        '93. Uvik isti (Grašo)',
        '94. Nevista (Grašo)',
        '95. Sporke rici (Grašo)',
        '96. Volim i postojim (Grašo)',
        '97. Vera od suvog zlata (Grašo)',
        '98. Tko nam brani (Grašo)',
        '99. Zdravko Čolić (Esma)',
        '100. Obriši suze (Begini)',
        '101. Pretjerujem (Ivan Zak)',
        '102. Za sve moje bivše (Begini)',
        '103. Usne varane (Ivan Zak)',
        '104. Devet slova jedne riči (Alen Nizetic)',
        '105. Kada žene tulumare (Jole)',
        '106. Remek djelo (Jole)',
        '107. Ima nesto od srca do srca (C. Jabuka)',
        '108. Dalmacijo srce oca moga (Ivana Kovac)',
        '109. To mi radi',
        '110. Svidja mi se ova stvar',
        '111. Tempera (Giboni)',
        '112. Posoljeni zrak i razlivena tinta (Giboni)',
        '113. Činim pravu stvar (Giboni)',
        '114. Sve ove godine (Indexi)',
        '115. Kad srce kaze da (Sandi)',
        '116. Što učinila si ti (Oliver)',
        '117. Lijepa li si (Thompson)',
        '118. Dalmatinac sam',
        '119. Dalmacija u mom oku',
        '120. Da te mogu pismom zvati',
        '121. Dalmatinka (Severina)',
        '122. Večeras je naša fešta',
        '123. Takav Sam Rođen (Mišo Kovač)',
        '124. Da Te Mogu Pismom Zvati (Klapa Maslina)',
        '125. Nosi Mi Se Bijela Boja (Jole)',
        '126. Dalmacijo Ljubav Si Vječna (Milo Hrnić)',
        '127. Majko Stara (Matko Jelavić)',
        '128. Srdele (Doris Dragović)',
        '129. Barka (Zaratino)',
        '130. Od Mora Do Mora (Daleka Obala)',
        '131. Stojin Na Kantunu (Đavoli)',
        '132. Moja Ljubav Stara (Klapa Godimenti)',
        '133. Ne Krij Oči Zelene (Bepo Matešić)',
        '134. Ja Sam Samo Vagabundo (Goran Karan)',
        '135. Šteta Duše Šteta Tila (Giuliano)',
        '136. Pričaj Mi Dalmaciju (Klapa Cambi)',
        '137. Uvik Isti (Petar Grašo)',
        '138. Noći U Dalmaciji (Klapa Bonaca)',
        '139. Ribari (Vinko Coce)',
        '140. Još Ne Mogu Pristat Volit (Klapa Iskon)',
        '141. Projdi Vilo (Gibonni)',
        '142. Sve Ću Preživit (Tedi Spalato)',
        '143. Ča Će Mi Copacabana (Oliver Dragojević)',
        '144. Plovi Mala Barka (Novi Fosili)',
        '145. Adio Bella (Jasna Zlokić)',
        '146. Tamo Gdje Sam Rođen (Tomislav Ivčić)',
        '147. Kad Mendule Procvitaju (Đani Maršan)',
        '148. Ne diraj moju ljubav (Klapa Šufit)',
        '149. Kuća Naše pisme (Goran Karan)',
        '150. Zora bila (Tomislav Bralić i klapa Intrade)',
        '151. Od zipke do križa (Klapa Cambi)',
        '152. Da te mogu pismom zvati (Klapa Maslina)',
        '153. Sunce mi od tebe dolazi (Klapa Rišpet i Mišo Kovač)',
        '154. Lipote gladan, jubavi žedan (Tedi Spalati i klapa Teuta)',
        '155. Ako si pošla spat (Klapa Šibenik i Mišo Kovač)',
        '156. Vilo moja (Klapa Crikvenica)',
        '157. Jute san se zajubija (Klapa Lučica)',
        '158. Ne more mi bit (Klapa Cambi)',
        '159. Ne damo te pismo naša (Tomislav Bralić i klapa Intrade)',
        '160. Kad je pošla ća (Klapa Rišpet)',
        '161. Škrinja jubavi (Tomislav Bralić i Oliver Dragojević)',
        '162. Kraj tvoje duše moje (Klapa Sv. Juraj HRM)',
        '163. Jubin te (Klapa Šufit)',
        '164. Oči boje lavande (Bonaca)',
        '165. Maslina je neobrana (Klapa Maslina)',
        '166. Aj ća, volin te (Klapa Kampanel)',
        '167. Dalmatino povišću pritrujena',
        '168. Mirno spavaj, ružo moja (Vinko Coce)',
        '169. Kalelarga (Tomislav Ivčić)',
        '170. Galeb i ja (Oliver Dragojević)',
        '171. Konoba (Meri Cetinić)',
        '172. Cvit od kamena (Dalmatino)',
        '173. More (Meri Cetinić)',
        '174. Noćas mi se snilo',
        '175. Kada umrem umotan u bilo (Vinko Coce)',
        '176. Stand by me (Ben E King)',
        '177. Simple the best (Tina Turner)',
        '178. Vivo per lei (Andrea Bocelli)',
        '179. Someone like you (Adele)',
        '180. Valerie (Amy Winehouse)',
        '181. Rolling In The Deep (Adele)',
        '182. Wonderfull tonight (Eric Klepton)',
        '183. The Time Of My Life (Bill Medley & Jennifer Warnes )',
        '184. Cocain (Eric Clapton)',
        '185. Without You (Mariah Carey)',
        '186. Lay down Saly (Eric Clapton)',
        '187. Proud Mary (Tina Turner)',
        '189. Walk of life (Dire Straits)',
        '190. Makarena (Gernte de Zona)',
        '191. Lets Get Loud (Jennifer Lopez)',
        '192. Green grass (Elvis)',
        '193. Sex bomb (Tom Jones)',
        '194. Its now of never (Elvis)',
        '195. Islands in the stream (Dolly Parton & Kenny Rogers )',
        '196. Rock around the clock (Elvis)',
        '197. Svatovska (Maja Šuput)',
        '198. Ja jos uvijek kao momak zivim (Mate Bulić)',
        '199. Djevojacko vece (Maja Šuput)',
        '200. Dao bi 100 Amerika (Jasmin Stavros)',
        '201. Dabogda se i ti udala (Mate Bulić)',
        '202. Otvor ženo kapiju (Miroslav Škoro)',
        '203. 5,6 piva (Mejaši)',
        '204. A kad mi dođeš ti (Oliver Dragojević)',
        '205. A šta da radim (Azra)',
        '206. Ako me ostaviš (Mišo Kovač)',
        '207. Ako odem prijatelji (Zlatko Pejaković)',
        '208. Ako poludim (Magazin)',
        '209. Ako su to samo bile laži (Plavi Orkestar)',
        '210. Ako varaš (Leo)',
        '211.Ako voliš me (Oliver Dragojević)',
        '212. Bitanga i princeza (Bijelo Dugme)',
        '213. Bižuterija (Jelena Rozga)',
        '214. Bolja od najbolje (Ivan Zak)',
        '215. Bolje biti pijan nego star (Plavi Orkestar)',
        '216. Da te ne volim (Novi fosili)',
        '217. Danas majko ženiš svoga sina',
        '218. Duša od papira (Jole)',
        '219. Dva zrna grožđa (Danijela)',
        '220. Hajde da ludujemo (Tajči)',
        '221. Heroj ulice (Prljavo kazalište)',
        '222. Još fališ (Vigor)',
        '223. Kad žena zavoli (Toni Cetinski)',
        '224. Krivi spoj (Severina)',
        '225. Milijun poljubaca (Gazde i Šola)',
        '226. Napala me s leđa (Begini)',
        '227. Lets twist again (Chubby Checker)',
        '228. I Cant Get No - Satisfaction (The Rolling Stones)',
        '229. Blue suede shoes (Elvis)',
        '230. La bamba (Ritchie Valens)',
        '231. Bad moon rising (Creedence Clearwater Revival)',
        '232. Living in the next door to alice (Smokie)',
        '233. California blue',
        '234. Country roads (John Denver)',
        '235. Pretty woman',
        '236. Suspicious minds (Elvis Presley)',
        '237. Hello Mary Lou',
        '238. La isla Bonita',
        '239. My number one',
        '240. Whenever, Wherever',
        '241. I will survive',
        '242. How long will I love you (Ellie Goulding)',
        '243. Diana (Paul Anka)',
        '244. Bonasera sinjorina',
        '245. Unchain my heart (Joe cocker)',
        '246. Sorry seems to be the hardest word',
        '247. Looking into my eyes (Bryan Adams)',
        '248. Ai se eu te pego (Michael Telo)',
        '249. La vida loca',
        '250. Country road',
        '251. Summer 69 (Bryan Adams)',
        '252. So far away (Dire Straits)',
        '253. Money for nothing (Dire Straits)',
        '254. Sultans of swing (Dire Straits)',
        '255. Nah neh nah (Vaya con dios)',
        '256. Dont Let The Sun Go Down On Me (George Michael & Elton John)',
        '257. Let it be (Beatles)',
        '258. Coco jambo',
        '259. Imagine (John Lennon)',
        '260. Twist And Shou (Beatles)',
        '261. Hey Jude (Beatles)',
        '262. Rolling in the Deep (Adele)',
        '263. Fleetwood Mac (Seven Wonders)',
        '264. All my loving (Beatles)',
        '265. Jumping Jack flash (Rolling Stones)',
        '266. Love somebody',
        '267. Hey tonight (Credence)',
        '​268. Bad moon rising (Credence)',
        '​269. Wild dances (Ruslana)',
        '270. No woman no cry (Bob Marley)',
        '271. Sunshine reggae (Bob Marley)',
        '272. I can see clearly now (Johny Nash)',
        '273. Lucile (Kenny Rogers)',
        '274. Yesterday (Beatles)',
        '275. Always on my mind (Willie Nelson)',
        '276. Me & Bobby Mc gee (Janis Joplin)',
        '277. Wurlitzer price (Willie Nelson & Norah Jones)',
        '278. Nikita (Elton John)',
        '279. Bomboleo (Gipsy Kings)',
        '280. Somethin stupid',
        '281. Whish you were here (Pink Floyd)',
        '282. The wall (Pink Floyd)',
        '283. Shine on your crazy diamond (Pink Floyd)',
        '284. Black magic woman (Santana)',
        '285. If tomorrow never comes (Ronan Keating)',
        '286. I Dont Want To Talk About It (Rod Stewart)',
        '287. Lambada',
        '288. Cesera',
        '289. Something stupid (Frank & Nancy Sinatra)',
        '290. Quanta La Mera',
        '291. Volara',
        '292. Lucille',
        '293. Layla',
        '294. I got you baby',
        '295. Every breath you take',
        '296. Moonlight shadow',
        '297. Can You Feel The Love Tonight (Elton John)',
        '298. Morska vila (Daleka obala)',
        '299. Ne zovi mama doktora (Prljavo kazalište)',
        '300. Nesanica (Toše Proeski)',
        '301. Odvest ću te na vjenčanje (Mišo Kovač)',
        '302. Otkad te nema (Alka Vuica)',
        '303. Ove noći jedna žena (Zlatko Pejaković)',
        '304. Previše suza u mom pivu (Prljavo kazalište)',
        '305. Prijatelji (Thompson)',
        '306. Prijateljice (Severina)',
        '307. Sad kad došla si (Klapa Kambi)',
        '308. Samac (Jole)',
        '309. Samo jedan dan života (Mišo Kovač)',
        '310. Samo je ljubav tajna dvaju svjetova (Thompson)',
        '311. Sanjao sam moju ružicu (Leteći odred)',
        '312. Sreća je tamo gdje si ti (Oliver Dragojević)',
        '313. Sve je lako kad si mlad (Prljavo kazalište)',
        '314. Takvi kao ti (Nina Badrić)',
        '315. Ti si moj san (Oliver i Kondža)',
        '316. Tko mi te krade (Ivan Zak)',
        '317. Viski (Lidija Bačić)',
        '318. Volio bih (Dubioza kolektiv)',
        '319. Za dobra stara vremena (Novi fosili)',
        '320. Za ljubav ja dao bih sve (Mladen Grdović i Bepo Metešić)',
        '321. Zavela me Ana (Mejaši)',
        '322. Zbog jedne divne crne žene (Kićo Slabinac)',
        '323. Zenica Blues (Zabranjeno pušenje)',
        '324. Četrnaest palmi (Daleka obala)',
        '325. Što učinio si ti (Nina Badrić)',
        '326. Ženo (Jasmin Stavros)',
        '327. Žuto lišće ljubavi (Oliver Dragojević)'
    ],
    searchTerm: ''
}

editSearchTerm=(e)=>{
    this.setState({searchTerm: e.target.value})
}

dynamicSearch=()=>{
    return this.state.names.filter(name=>name.toLowerCase().includes(this.state.searchTerm.toLowerCase()))
}

render(){
    return(
        <div >
            <div className={styles.repertoire_page}>
            <div className={styles.searchContainer}>
                <FontAwesomeIcon icon={faSearch}  className={styles.repertoire_h2}></FontAwesomeIcon>
                <input type='text' value={this.state.searchTerm} onChange={this.editSearchTerm} placeholder="Pretraži repertoar!"/>
            </div>
            <br></br>
            <h1 className={styles.repertoire_h1}>Sve pjesme:</h1>
            <br></br>
            <div className={styles.NamesContainer}>
                <NamesContainer names={this.dynamicSearch()}/>
            </div>
            </div>
        </div>
    ); 
}
}

export default Songs;